defaults:
  actions:
    queue:
      allow_merging_configuration_change: true

queue_rules:
  - name: default
    queue_conditions:
      - check-success=buildbot/nix-eval
    priority_rules:
      - name: high-priority
        conditions:
          - label=priority-urgent
        priority: high
      - name: low-priority
        conditions:
          - label=priority-low
        priority: low

pull_request_rules:
  - name: Automerge PRs using the merge queue
    conditions:
      - label~=merge-queue|automerge
      - base=main
    actions:
      queue:
        name: default
        method: squash

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
