queue_rules:
  - name: default
    conditions:
      - "check-success=buildbot/nix-build"
    batch_size: 1
    batch_max_wait_time: "15 minutes"
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      
      {{ body }}

pull_request_rules:
  - name: Automerge PRs using the merge queue
    conditions:
      - "label=merge-queue"
      - "base=main"
    actions:
      queue:
        name: default
      delete_head_branch:
        force: true

  - name: Delete head branch after merge
    conditions:
      - "closed"
      - "merged"
    actions:
      delete_head_branch: {}
