# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.html", "*.json", "*.md", "*.yml", "*.yaml", "*.md"]
