# Build and deploy MkDocs to gh-pages for main branch
name: docs
on:
  push:
    branches:
      - main
      - feat/expose-docs-site
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        with:
          name: nix-community
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: "Deploy docs"
        run: nix run .#deploy-docs